# Generated by Django 5.0.3 on 2024-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='token',
            field=models.CharField(default='mamadoudjouma', max_length=120),
            preserve_default=False,
        ),
    ]
