# Generated by Django 5.0.3 on 2024-04-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0003_alter_utilisateur_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
