# Generated by Django 5.0.3 on 2024-04-24 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0003_rename_media_technique_culture_video_and_more'),
        ('Compte', '0004_delete_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commentaire', models.DateTimeField(auto_now=True)),
                ('contenue', models.TextField()),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomie.actualite')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
