# Generated by Django 5.0.3 on 2024-05-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0005_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notification',
            name='destinateur',
        ),
        migrations.AddField(
            model_name='notification',
            name='destinateur',
            field=models.ManyToManyField(related_name='destinateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
