# Generated by Django 5.0.3 on 2024-05-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0006_notification_utilisateur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
