# Generated by Django 5.0.3 on 2024-05-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0011_alter_actualite_date_pub'),
        ('Compte', '0007_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_notif', models.CharField(max_length=150)),
                ('contenue', models.TextField()),
                ('date_notif', models.DateTimeField(auto_now=True)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomie.actualite')),
                ('destinateur', models.ManyToManyField(related_name='destinateur', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
