# Generated by Django 5.0.3 on 2024-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='notif',
            field=models.ManyToManyField(default='', related_name='notif', to='Compte.notification'),
        ),
    ]
