# Generated by Django 5.0.3 on 2024-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0010_remove_notification_destinateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_notif',
            field=models.BooleanField(default=False),
        ),
    ]
