# Generated by Django 5.0.3 on 2024-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0011_notification_read_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_forum',
            old_name='forum_id',
            new_name='forum',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='notif',
            field=models.ManyToManyField(default='', related_name='notifs', to='Compte.notification'),
        ),
    ]
