# Generated by Django 5.0.3 on 2024-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compte', '0012_rename_forum_id_message_forum_forum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chats'),
        ),
    ]
