# Generated by Django 5.0.1 on 2024-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('media', models.FileField(upload_to='')),
                ('contenu', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='culture')),
                ('nom_culture', models.CharField(max_length=50)),
                ('description_culture', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Endroit_propice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_endroit', models.CharField(max_length=50)),
                ('nom_ville', models.CharField(max_length=50)),
                ('description_endroit', models.TextField()),
                ('periode_plantation', models.DateField()),
                ('periode_recolte', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Technique_culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_technique', models.CharField(max_length=50)),
                ('description_technique', models.TextField()),
                ('media', models.FileField(upload_to='')),
            ],
        ),
    ]
