# Generated by Django 5.0.3 on 2024-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0003_rename_media_technique_culture_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endroit_propice',
            name='culture',
        ),
        migrations.AddField(
            model_name='culture',
            name='endroit_propice',
            field=models.ManyToManyField(to='Agronomie.endroit_propice'),
        ),
    ]
