# Generated by Django 5.0.3 on 2024-04-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0005_periode_culture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endroit_propice',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='endroit_propice',
        ),
        migrations.DeleteModel(
            name='Periode_culture',
        ),
        migrations.DeleteModel(
            name='Endroit_propice',
        ),
    ]
