# Generated by Django 5.0.3 on 2024-04-28 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0007_endroit_propice_culture_endroit_propice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndroitPropice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_endroit', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('desc_endroit', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='culture',
            name='endroit_propice',
        ),
        migrations.CreateModel(
            name='PeriodeDePlantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomie.culture')),
                ('endroit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomie.endroitpropice')),
            ],
        ),
    ]
