# Generated by Django 5.0.3 on 2024-04-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0008_endroitpropice_remove_culture_endroit_propice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endroit_propice',
        ),
    ]
