# Generated by Django 5.0.3 on 2024-04-29 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0009_delete_endroit_propice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 0, 10, 48, 747786, tzinfo=datetime.timezone.utc)),
        ),
    ]
