# Generated by Django 5.0.3 on 2024-04-29 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomie', '0010_alter_actualite_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
