# Generated by Django 5.0.1 on 2024-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel_culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ressource')),
                ('user', models.CharField(max_length=50)),
                ('nom_materiel', models.CharField(max_length=50)),
                ('description_materiel', models.TextField()),
                ('disponibilite', models.BooleanField(default=False)),
                ('prix', models.IntegerField()),
                ('lieu_vente', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_ressource', models.CharField(max_length=50)),
                ('description_ressource', models.TextField()),
                ('media', models.FileField(upload_to='')),
            ],
        ),
    ]
